steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/devops-464507/gcr.io/cicd-1-image', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/devops-464507/gcr.io/cicd-1-image']

options:
  logging: CLOUD_LOGGING_ONLY
